### PR TITLE
Update react-native-sesitive-info to v6

### PR DESCRIPTION
**Pull request by mkilp**
I updated the requirements to the new react-native-sensitive-info v6.

All tests still work fine and as expected.

### CODE REVIEW

**Comment by quangHelloSelf** [comment]
Hi @frank-west-iii - any chance we can get this merged?

**Comment by frank-west-iii** [comment]
Hey @quangHelloSelf, I am no longer working at Zeal so I don't have commit bit on this repo anymore and don't use redux anymore either.  

Might want to touch base with @acuppy to see who might be your best contact for this repo.

**Comment by quangHelloSelf** [comment]
Hi @frank-west-iii thanks so much for your reply - I wish you all the best on your current endeavours.

**Review by AndersonVanzo — APPROVED** [review]
Solve the problem and all tests work fine

**Comment by mkilp** [comment]
Any update when this will be merged? Thanks!
@quangHelloSelf Updated peer dependencies as well.

**Comment by yahacom** [comment]
Guys, it's need to be merged.
@acuppy any chance you can help with it?

**Comment by AndersonVanzo** [comment]
@acuppy @tyarrish @craineum any chance of this being merged?

**Review by acuppy — APPROVED** [review]

**Pull request merged**
